import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { I18nProvider } from "@/lib/providers/i18n-provider";
import { QueryProvider } from "@/lib/providers/query-provider";

import type { Metadata } from "next";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yubi App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // NOTE: lang="en" is fixed at SSR time. Client-side language detection
    // happens in I18nProvider via useEffect, which causes a brief flash of
    // English content for non-English browsers. This will be improved with
    // middleware/cookie-based SSR detection in a future PR.
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <I18nProvider>
            <QueryProvider>{children}</QueryProvider>
          </I18nProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
