package entity

var Models = []any{
	&Organization{},
	&User{},
	&OrganizationMembership{},
	&Site{},
	&Location{},
	&Task{},
	&Robot{},
	&TaskVersion{},
	&SubTask{},
	&Episode{},
	&EpisodeGrade{},
	&EpisodeSubTask{},
	&EpisodeSubTaskExecution{},
	&EpisodeStatsHourly{},
	&EpisodeStatsDaily{},
	&EpisodeStatsMonthly{},
	&TaskVersionStats{},
	&TaskCategoryType{},
	&TaskTag{},
	&TaskTagAssignment{},
	&UserLocationAssignment{},
	&UserSiteAssignment{},
	&RobotUptimeHourly{},
	&APIKey{},
}

var TableCreators = []TableQueryCreator{
	UserTableCreator,
	OrganizationMembershipTableCreator,
	SiteTableCreator,
	LocationTableCreator,
	RobotTableCreator,
	TaskTableCreator,
	TaskVersionTableCreator,
	SubTaskTableCreator,
	EpisodeTableCreator,
	EpisodeGradeTableCreator,
	EpisodeSubTaskTableCreator,
	EpisodeSubTaskExecutionTableCreator,
	EpisodeStatsHourlyTableCreator,
	EpisodeStatsDailyTableCreator,
	EpisodeStatsMonthlyTableCreator,
	TaskVersionStatsTableCreator,
	TaskCategoryTypeTableCreator,
	TaskTagTableCreator,
	TaskTagAssignmentTableCreator,
	UserLocationAssignmentTableCreator,
	UserSiteAssignmentTableCreator,
	RobotUptimeHourlyTableCreator,
	APIKeyTableCreator,
}

var IdxCreators = [][]IndexQueryCreator{
	EpisodeIdxCreators,
	EpisodeGradeIdxCreators,
	UserIdxCreators,
	OrganizationMembershipIdxCreators,
	TaskIdxCreators,
	TaskVersionIdxCreators,
	SubTaskIdxCreators,
	RobotIdxCreators,
	LocationIdxCreators,
	SiteIdxCreators,
	EpisodeStatsHourlyIdxCreators,
	EpisodeStatsDailyIdxCreators,
	EpisodeStatsMonthlyIdxCreators,
	TaskVersionStatsIdxCreators,
	UserLocationAssignmentIdxCreators,
	UserSiteAssignmentIdxCreators,
	RobotUptimeHourlyIdxCreators,
	EpisodeSubTaskExecutionIdxCreators,
	APIKeyIdxCreators,
}
